name: dna-diffusion
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - accelerate=1.5.2
  - blas=1.0
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2025.2.25
  - certifi=2025.1.31
  - charset-normalizer=3.3.2
  - deprecated=1.2.13
  - diffusers=0.32.2
  - diffusers-base=0.32.2
  - diffusers-torch=0.32.2
  - easydict=1.13
  - einops=0.8.1
  - expat=2.6.4
  - filelock=3.13.1
  - freetype=2.12.1
  - fsspec=2024.12.0
  - gmp=6.3.0
  - gmpy2=2.2.1
  - huggingface_accelerate=1.4.0
  - huggingface_hub=0.29.2
  - idna=3.7
  - importlib-metadata=8.5.0
  - jinja2=3.1.6
  - jpeg=9e
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libcxx=20.1.1
  - libdeflate=1.22
  - libexpat=2.6.4
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libopenblas=0.3.21
  - libpng=1.6.39
  - libprotobuf=4.25.3
  - libsqlite=3.46.0
  - libtiff=4.5.1
  - libtorch=2.5.1
  - libuv=1.48.0
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - lightning-utilities=0.11.9
  - llvm-openmp=20.1.1
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - ncurses=6.4
  - networkx=3.4.2
  - nomkl=3.0
  - numpy=2.0.1
  - numpy-base=2.0.1
  - openjpeg=2.5.2
  - openssl=3.4.1
  - opentelemetry-api=1.30.0
  - packaging=24.2
  - perl=5.32.1
  - pillow=11.1.0
  - pip=25.0
  - psutil=5.9.0
  - pysocks=1.7.1
  - python=3.12.2
  - python_abi=3.12
  - pytorch=2.5.1
  - pytorch-lightning=2.5.1
  - pyyaml=6.0.2
  - readline=8.2
  - regex=2024.11.6
  - requests=2.32.3
  - safetensors=0.5.3
  - setuptools=75.8.0
  - sleef=3.5.1
  - sqlite=3.45.3
  - sympy=1.13.3
  - tk=8.6.14
  - torchmetrics=1.2.1
  - tqdm=4.67.1
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2025a
  - urllib3=2.3.0
  - viennarna=2.7.0
  - wheel=0.45.1
  - wrapt=1.17.0
  - xz=5.6.4
  - yaml=0.2.5
  - zipp=3.21.0
  - zlib=1.2.13
  - zstd=1.5.6
